### PR TITLE
lowercase p for protobuf dep

### PR DESCRIPTION
**Pull request by flynneva**

### CODE REVIEW

**Comment by flynneva** [comment]
@rex-schilasky might be better at finding what other dependencies are listed...but if we add them to the `package.xml` file and use `rosdep install` it should install them if we use the [**rosdep keys** available](https://github.com/ros/rosdistro/blob/fad755ccde1749a1ea4b2419712ee31296604eb4/rosdep/base.yaml#L5422)

**Comment by flynneva** [comment]
all the dependencies that are left for manual installation are:
```
      - name: install eCAL bionic dependencies
        if: matrix.os_release == 'bionic'
        run: 'sudo apt install -y libc6 libcurl4 libgcc1 libhdf5-100'
      - name: install eCAL focal dependencies
        if: matrix.os_release == 'focal'
        run: 'sudo apt install -y libc6 libcurl4 libgcc1 libhdf5-103'
```

**Comment by brakmic-aleksandar** [comment]
I don't think we should add QT5 dependencies to package.xml file because they aren't RMW dependencies.

**Review by brakmic-aleksandar — COMMENTED** [review]
I don't think we should add QT5 dependencies to package.xml file because they aren't RMW dependencies.

**Comment by flynneva** [comment]
good point

**Comment by flynneva** [comment]
@rex-schilasky or @brakmic-aleksandar i went ahead and ran `ament_copyright --add-missing "Continental AG" apache2 to add in ROS2 CI-compliant copyright info.

I can delete it if you'd rather keep the other way, just if we do it this way then it will be able to pass the normal ROS2 CI `ament_copyright` tests.

**Comment by flynneva** [comment]
there is something going on with importlib-metadata during the builds. tracking this with [this issue here over on the setup-ros action](https://github.com/ros-tooling/setup-ros/issues/278)

**Comment by flynneva** [comment]
did we want to start fixing linting errors too? running `ament_cpplint` results in 4709 linting errors.

**Comment by rex-schilasky** [comment]
> @rex-schilasky or @brakmic-aleksandar i went ahead and ran `ament_copyright --add-missing "Continental AG" apache2 to add in ROS2 CI-compliant copyright info.
> 
> I can delete it if you'd rather keep the other way, just if we do it this way then it will be able to pass the normal ROS2 CI `ament_copyright` tests.

That fits from my point of view. We should try as much as possible make this ROS compliant.

**Comment by rex-schilasky** [comment]
> did we want to start fixing linting errors too? running `ament_cpplint` results in 4709 linting errors.

Where can I see the log of this check ? Thank you for investing so many effort in get the CI run !

**Comment by flynneva** [comment]
on the CI it unfortunately isnt getting to the `colcon test` step and failing on the step before `colcon build`.

ill see what i can do today and let you know once it gets to that step.

**Comment by flynneva** [comment]
as a side note ill squash all these commits into a single one once this is working properly

**Comment by flynneva** [comment]
@rex-schilasky and @brakmic-aleksandar, it looks like its building now for all ubuntu ROS2 distros (Ubuntu 18.04 and Ubuntu 20.04 OS's). shortly we should be able to add in OSX and Windows to the CI, but this should be a good start.

[here you can see the cpplint errors](https://github.com/continental/rmw_ecal/pull/7/checks?check_run_id=1448793729#step:12:210) I mentioned before.

it still looks like there is one error during the build, something to do with [windeployqtplot not having a parent.](https://github.com/continental/rmw_ecal/pull/7/checks?check_run_id=1448793729#step:12:84) maybe one of you know how to fix this error?

**Comment by brakmic-aleksandar** [comment]
> did we want to start fixing linting errors too? running `ament_cpplint` results in 4709 linting errors.

From what i can see vast majority of linting errors are due to project using tabs instead of spaces...
I'd rather focus on having whole CI process working fine, with linting erros, and focus on them afterwards.

**Comment by rex-schilasky** [comment]
> did we want to start fixing linting errors too? running `ament_cpplint` results in 4709 linting errors.

I fixed the usage of tabulators in a separate branch, hope we can soon merge our 2 branches and check again

**Comment by flynneva** [comment]
@rex-schilasky most of this branch is just the fixing of the gh actions + copyright formatting stuff. I could squash this down into one commit and then this would be ready for merge.

**Comment by flynneva** [comment]
@rex-schilasky  or @brakmic-aleksandar all set for merge i think

**Pull request merged**
